<a href="https://colab.research.google.com/github/patison5/FAIntelligence/blob/main/Pygmo_%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Инициализация

In [1]:
!pip install PyGMO

In [2]:
import numpy as np
import pygmo as pg
import sympy as sy

In [3]:
def P4MultiSym():
    xs = [sy.Symbol('x'+str(i)) for i in range(2)]
    PI = sy.pi
    f = xs[0] * sy.sin(4 * PI * xs[0]) + xs[1] * sy.sin(4 * PI * xs[1])
    return f, xs

def P4Multi(x, y):
    ''' 
        Мультифункция (рис П.3)
        Глобальный экстремум Z = 837,9657 
    '''
    return x * np.sin(4 * np.pi * x) + y * np.sin(4 * np.pi * y)

def get_fn_resultSingle(df, x0, xs):
    ''' 
        Вернуть числовой результат частных производных символьно заданной функции для одного параметра x, y
        df - массив частных производных функции
        x0 - массив входных данных [x, y]
    '''
    variables = [(xs[i], x0[i]) for i in range(len(xs))] # -> [(x0, 1.0), (x1, 2.0)]
    return np.double(df.subs(variables))

In [4]:
f, xs = P4MultiSym()
f, xs

(x0*sin(4*pi*x0) + x1*sin(4*pi*x1), [x0, x1])

In [5]:
prob = pg.problem(pg.rosenbrock(dim = 5))
# print(prob)

In [37]:
class My_MultiFunction:
    def __init__(self, dim):
        self.dim = dim

    def fitness(self,x):
      print(x)
      print(get_fn_resultSingle(f, x, xs))
      return [get_fn_resultSingle(f, x, xs)]

    def get_bounds(self):
        return (np.full((self.dim,),-2.),np.full((self.dim,),2.))

In [50]:
prob = pg.problem(My_MultiFunction(5))

In [51]:
print(prob) 

Problem name: <class '__main__.My_MultiFunction'>
	C++ class name: pybind11::object

	Global dimension:			5
	Integer dimension:			0
	Fitness dimension:			1
	Number of objectives:			1
	Equality constraints dimension:		0
	Inequality constraints dimension:	0
	Lower bounds: [-2, -2, -2, -2, -2]
	Upper bounds: [2, 2, 2, 2, 2]
	Has batch fitness evaluation: false

	Has gradient: false
	User implemented gradient sparsity: false
	Has hessians: false
	User implemented hessians sparsity: false

	Fitness evaluations: 0

	Thread safety: none



In [52]:
algo = pg.algorithm(pg.bee_colony(gen = 20, limit = 20))
algo.set_verbosity(1)
pop = pg.population(prob, 2)
# pop = algo.evolve(pop)
print(pop.champion_f) 

[-1.61018167 -0.84495784 -1.35905193  1.51588975 -1.62754657]
0.7968885933391072
[ 0.15967269 -0.48192149  1.83312994  1.81909264  0.95403926]
0.0362103616332662
[0.03621036]


In [53]:
n_pygmo = pop.get_x().shape[0]
print(pop)
print(n_pygmo)

Problem name: <class '__main__.My_MultiFunction'>
	C++ class name: pybind11::object

	Global dimension:			5
	Integer dimension:			0
	Fitness dimension:			1
	Number of objectives:			1
	Equality constraints dimension:		0
	Inequality constraints dimension:	0
	Lower bounds: [-2, -2, -2, -2, -2]
	Upper bounds: [2, 2, 2, 2, 2]
	Has batch fitness evaluation: false

	Has gradient: false
	User implemented gradient sparsity: false
	Has hessians: false
	User implemented hessians sparsity: false

	Fitness evaluations: 2

	Thread safety: none

Population size: 2

List of individuals: 
#0:
	ID:			11025816436708392331
	Decision vector:	[-1.61018, -0.844958, -1.35905, 1.51589, -1.62755]
	Fitness vector:		[0.796889]
#1:
	ID:			14895778606186348212
	Decision vector:	[0.159673, -0.481921, 1.83313, 1.81909, 0.954039]
	Fitness vector:		[0.0362104]

Champion decision vector: [0.159673, -0.481921, 1.83313, 1.81909, 0.954039]
Champion fitness: [0.0362104]

2


In [54]:
pop = algo.evolve(pop)
n_pygmo = pop.get_x().shape[0]
print(pop)

[-1.61018167 -0.84495784 -1.35905193  1.51588975 -1.1850494 ]
0.7968885933391072
[ 0.15967269 -0.1498699   1.83312994  1.81909264  0.95403926]
0.28736484739598206
[ 0.15967269 -0.79770883  1.83312994  1.81909264  0.95403926]
-0.3053541763560758
[ 0.15967269 -0.77160313  1.83312994  1.81909264  0.95403926]
-0.0621514033865299
[-1.61018167 -0.84495784 -1.35905193  1.51588975  0.82524139]
0.7968885933391072
[ 0.15967269 -0.8347458   1.83312994  1.81909264  0.95403926]
-0.5854504457366354
[ 0.15967269 -0.8347458   2.          1.81909264  0.95403926]
-0.5854504457366354
[-2.         -0.84495784 -1.35905193  1.51588975 -1.62754657]
-0.7854570071818713
[-2.         -0.84495784 -2.          1.51588975 -1.62754657]
-0.7854570071818713
[ 0.15967269 -0.84054263  1.83312994  1.81909264  0.95403926]
-0.6182138143961263
[-0.1660624  -0.84495784 -1.35905193  1.51588975 -1.62754657]
-0.6410164097635747
[-2.         -0.84495784 -1.35905193  1.29148781 -1.62754657]
-0.7854570071818713
[-2.         -0.84